// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "CommentModel.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray<id> *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static id GetNullableObjectAtIndex(NSArray<id> *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface CommentModel ()
+ (CommentModel *)fromList:(NSArray<id> *)list;
+ (nullable CommentModel *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@implementation CommentModel
+ (instancetype)makeWithPostId:(nullable NSNumber *)postId
    id:(nullable NSNumber *)id
    name:(nullable NSString *)name
    email:(nullable NSString *)email
    body:(nullable NSString *)body {
  CommentModel* pigeonResult = [[CommentModel alloc] init];
  pigeonResult.postId = postId;
  pigeonResult.id = id;
  pigeonResult.name = name;
  pigeonResult.email = email;
  pigeonResult.body = body;
  return pigeonResult;
}
+ (CommentModel *)fromList:(NSArray<id> *)list {
  CommentModel *pigeonResult = [[CommentModel alloc] init];
  pigeonResult.postId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.id = GetNullableObjectAtIndex(list, 1);
  pigeonResult.name = GetNullableObjectAtIndex(list, 2);
  pigeonResult.email = GetNullableObjectAtIndex(list, 3);
  pigeonResult.body = GetNullableObjectAtIndex(list, 4);
  return pigeonResult;
}
+ (nullable CommentModel *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [CommentModel fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.postId ?: [NSNull null],
    self.id ?: [NSNull null],
    self.name ?: [NSNull null],
    self.email ?: [NSNull null],
    self.body ?: [NSNull null],
  ];
}
@end

@interface nullCommentModelPigeonCodecReader : FlutterStandardReader
@end
@implementation nullCommentModelPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 129: 
      return [CommentModel fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface nullCommentModelPigeonCodecWriter : FlutterStandardWriter
@end
@implementation nullCommentModelPigeonCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[CommentModel class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface nullCommentModelPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation nullCommentModelPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[nullCommentModelPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[nullCommentModelPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *nullGetCommentModelCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    nullCommentModelPigeonCodecReaderWriter *readerWriter = [[nullCommentModelPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}
void SetUpCommentApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<CommentApi> *api) {
  SetUpCommentApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpCommentApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<CommentApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  /// Sets the base URL configuration.
  /// The native side should store these values and use them to construct the
  /// URL.
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.comments_repository.CommentApi.setBaseUrl", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetCommentModelCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setBaseUrlScheme:authority:port:error:)], @"CommentApi api (%@) doesn't respond to @selector(setBaseUrlScheme:authority:port:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_scheme = GetNullableObjectAtIndex(args, 0);
        NSString *arg_authority = GetNullableObjectAtIndex(args, 1);
        NSInteger arg_port = [GetNullableObjectAtIndex(args, 2) integerValue];
        FlutterError *error;
        [api setBaseUrlScheme:arg_scheme authority:arg_authority port:arg_port error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  /// Returns a list of [CommentModel] instances for the given postId.
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.comments_repository.CommentApi.getComments", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetCommentModelCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getCommentsPostId:error:)], @"CommentApi api (%@) doesn't respond to @selector(getCommentsPostId:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_postId = [GetNullableObjectAtIndex(args, 0) integerValue];
        FlutterError *error;
        NSArray<CommentModel *> *output = [api getCommentsPostId:arg_postId error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
