include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    one_member_abstracts: ignore

  exclude:
    - "**.g.dart"
    - "**.pb.dart"
    - "**.pbenum.dart"
    - "**.pbjson.dart"
    - "**.pbserver.dart"
